# Generated by Django 2.0.6 on 2018-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Study_id', models.CharField(max_length=200)),
                ('Run_id', models.CharField(max_length=200)),
                ('Assay_type', models.CharField(max_length=200)),
                ('Genotype', models.CharField(max_length=200)),
                ('Treatment', models.CharField(max_length=200)),
                ('Dev', models.CharField(max_length=200)),
                ('Tissue', models.CharField(max_length=200)),
                ('Layout', models.CharField(max_length=200)),
                ('Gene_id', models.CharField(max_length=200)),
                ('Tpm', models.CharField(max_length=200)),
                ('Treatment_codenumber', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'leeu',
            },
        ),
    ]
