# Generated by Django 2.0.6 on 2018-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConMJSA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
