# Generated by Django 2.0.6 on 2018-07-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConMJSA', '0002_auto_20180706_1149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms',
            table='cms',
        ),
    ]
