# Generated by Django 2.0.6 on 2018-07-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConMJSA', '0003_auto_20180707_0746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms',
            table='cm',
        ),
    ]
