# Generated by Django 2.0.6 on 2018-07-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConMJSA', '0006_auto_20180707_0830'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms',
            table='cmssss',
        ),
    ]
